package entity

class Map(isAutoGenerated: Boolean) {
    private val boats = arrayListOf<Boat>()
    val cells: ArrayList<ArrayList<Point>> = ArrayList()

    init {
        TODO("Init arrayList; auto generate")
    }

    private fun autoGen() {
        TODO("GENERATE")
    }

    fun setBoat(x: Int, y: Int, size: Int, isHorizontal: Boolean): Boolean {
        TODO()
    }

    private fun hasNoCollisions(x: Int, y: Int): Boolean {
        TODO()
    }

    private fun isEmptyOrOutOfMap(x: Int, y: Int): Boolean {
        TODO()
    }

    fun hit(x: Int, y: Int): HitState {
        TODO()
    }

    private fun setHit(x: Int, y: Int) {
        TODO()
    }

    fun isFleetDead(): Boolean {
        TODO()
    }

    enum class HitState {
        Hit, Miss, Empty, Error
    }
}
