import androidx.compose.runtime.MutableState
import androidx.compose.runtime.mutableStateOf
import entity.Map

class Game {
    var playersMap = Map(isAutoGenerated = true)
    var botsMap = Map(isAutoGenerated = true)
    var state: MutableState<GameState>
    private var mapState = PrepareState()
    var textState = ""
    enum class GameState(val textState: String) {
        WaitingState("Ожидайте"),
        Prepare("Расстановка кораблей."),
        PlayersTurn("Ваш ход"),
        BotsTurn("Ход бота"),
        PlayersWin("Вы победили!!!"),
        BotsWin("Вы проиграли :("),
        Error("Критическая ошибка")
    }

    init {
        state = mutableStateOf(GameState.Prepare)
    }

    fun botHit() {

    }

    fun restart() {

    }

    fun checkGameState() {

    }

    internal class PrepareState {

    }

}
